In [1]:
import numpy as np     # scientific calculation
import pandas as pd    # handle csv file
import seaborn as sns  # visualize 
import matplotlib.pyplot as plt # plotting

In [2]:
df =pd.read_csv('RFM_clear.csv')

In [4]:
df=df.rename(columns={'R_Quartile':'R','F_Quartile':'F','M_Quartile':'M'})

In [5]:
df['RFM_Score'] = df.R.astype(str)+ df.F.astype(str) + df.M.astype(str)
df.drop(df.tail(1).index,inplace=True)
df

,Unnamed: 0,CustomerID,InvoiceDate,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,...,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY,All,recency,frequency,monetary,R,F,M,RFM_Score
0,0,12347.0,2011/12/7,0,0,0,0,0,0,0,...,0,0,11,2.0,7.0,4310.00,5,5,5,555
1,1,12348.0,2011/9/25,0,0,0,0,0,0,0,...,0,0,3,75.0,4.0,1797.24,2,4,4,244
2,2,12349.0,2011/11/21,0,0,0,0,0,0,0,...,0,0,73,18.0,1.0,1757.55,4,1,4,414
3,3,12350.0,2011/2/2,0,0,0,0,0,0,0,...,0,0,17,310.0,1.0,334.40,1,1,2,112
4,4,12352.0,2011/11/3,0,0,0,0,0,0,0,...,0,0,15,36.0,7.0,1545.41,3,5,4,354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4364,4364,18277.0,2011/10/12,0,0,0,0,0,0,0,...,0,0,8,58.0,2.0,97.63,3,2,1,321
4365,4365,18278.0,2011/9/27,0,0,0,0,0,0,0,...,0,0,9,73.0,1.0,173.90,2,1,1,211
4366,4366,18280.0,2011/3/7,0,0,0,0,0,0,0,...,0,0,10,277.0,1.0,180.60,1,1,1,111
4367,4367,18281.0,2011/6/12,0,0,0,0,0,0,0,...,0,0,7,180.0,1.0,80.82,1,1,1,111
4368,4368,18282.0,2011/12/2,0,0,0,0,0,0,0,...,0,0,5,7.0,3.0,176.60,5,3,1,531

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop(labels=['InvoiceDate','R','F','M','RFM_Score'],axis=1).values
Y = df['RFM_Score'].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=160)

print('train shape:', X_train.shape)
print('test shape:', X_test.shape)

train shape: (3495, 3902)
test shape: (874, 3902)

In [7]:
Y_test = Y_test.astype(int)

In [8]:
from sklearn.ensemble import RandomForestRegressor

#10個決策樹
rf = RandomForestRegressor(n_estimators= 10, random_state=42)
rf.fit(X_train, Y_train)

RandomForestRegressor(n_estimators=10, random_state=42)

In [9]:
predictions = rf.predict(X_test)
predictions=np.around(predictions)

In [10]:
predictions=predictions.astype(int)

In [11]:
i=0
k=0

for n in range(len(predictions)):
    if predictions[n] == Y_test[n]:
        i+=1
    k+=1
    
rate= (i/k)*100
rate=str(round(rate,2))

print('precise rate : '+ rate + "%")

precise rate : 98.05%

# Only give recency

In [12]:
from sklearn.model_selection import train_test_split
X = df.drop(labels=['InvoiceDate','All','frequency','monetary','R','F','M','RFM_Score'],axis=1).values
Y = df['RFM_Score'].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=160)

Y_test = Y_test.astype(int)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators= 10, random_state=42)
rf.fit(X_train, Y_train)

predictions = rf.predict(X_test)
predictions=np.around(predictions)
predictions=predictions.astype(int)

i=0
k=0

for n in range(len(predictions)):
    if predictions[n] == Y_test[n]:
        i+=1
    k+=1
    
rate= (i/k)*100
rate=str(round(rate,2))

print('precise rate : '+ rate + "%")

precise rate : 3.55%

# Give recency, frequency

In [13]:
from sklearn.model_selection import train_test_split
X = df.drop(labels=['InvoiceDate','All','monetary','R','F','M','RFM_Score'],axis=1).values
Y = df['RFM_Score'].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=160)

Y_test = Y_test.astype(int)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators= 10, random_state=42)
rf.fit(X_train, Y_train)

predictions = rf.predict(X_test)
predictions=np.around(predictions)
predictions=predictions.astype(int)

i=0
k=0

for n in range(len(predictions)):
    if predictions[n] == Y_test[n]:
        i+=1
    k+=1
    
rate= (i/k)*100
rate=str(round(rate,2))

print('precise rate : '+ rate + "%")

precise rate : 47.25%

# Give recency, frequency, monetary

In [14]:
from sklearn.model_selection import train_test_split
X = df.drop(labels=['InvoiceDate','All','R','F','M','RFM_Score'],axis=1).values
Y = df['RFM_Score'].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=160)

Y_test = Y_test.astype(int)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators= 10, random_state=42)
rf.fit(X_train, Y_train)

predictions = rf.predict(X_test)
predictions=np.around(predictions)
predictions=predictions.astype(int)

i=0
k=0

for n in range(len(predictions)):
    if predictions[n] == Y_test[n]:
        i+=1
    k+=1
    
rate= (i/k)*100
rate=str(round(rate,2))

print('precise rate : '+ rate + "%")

precise rate : 98.28%